server:
  port:
  servlet:
    context-path: /conformity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123
    data:
        mongodb:
          uri: mongodb://localhost:27017
          database: car


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000





